export const AI_AGENTS_COMPONENTS = [
  {
    src: "/schoolcalender.jpg",
    title: "学位安排",
    sub: "山西大学2025年度学位工作日程安排。",
    navigate: "chat/dJUIt21U3NQ2yi0p",
  },
  {
    src: "/finacial.jpg",
    title: "山大财务助手",
    sub: "山西大学计划财务处服务手册。",
    navigate: "chat/FfjVY5knvF0fgIEa",
  },
  {
    src: "/conference.jpg",
    title: "会议摘要",
    sub: "会议摘要生成。",
    navigate: "chat/hGafV3zAQHRp5Xyj",
  },
  {
    src: "/interview.jpg",
    title: "AI 前端面试官",
    sub: "一个模拟的前端面试官，通过提问测试前端开发的技能水平。",
    navigate: "chat/PasFhwWOEC1Q2Dys",
  },
  {
    src: "/python.jpg",
    title: "Python漏洞修复",
    sub: "Python漏洞修复。",
    navigate: "chat/0GC8KIVMwwQv7uhM",
  },
  {
    src: "/code.jpg",
    title: "代码转换器",
    sub: "这是一款能转换多种编程语言代码片段的应用程序。您可以输入要转换的代码，选择目标编程语言，然后获得所需的输出结果。",
    navigate: "completion/ryB3cdCjjx33Wx9B",
  },
  {
    src: "/deepresearch.jpg",
    title: "DeepResearch",
    sub: "深度探索。",
    navigate: "chat/cMmLdZwRpqKGHRHQ",
  },
  {
    src: "/DeepSeek_logo.png",
    title: "联网搜索",
    sub: "DeepSeek-R1联网搜索。",
    navigate: "chat/izojRUlZJ4r8LiqI",
  },
  {
    src: "/webpage.webp",
    title: "网页生成",
    sub: "网页生成器。",
    navigate: "chat/2gLTM41D6fyCAG8V",
  },
  // {
  //   src: "/school.jpg",
  //   title: "山大AI校园",
  //   sub: "山大AI校园小助手，为您的校园生活保驾护航。",
  //   navigate: "dJUIt21U3NQ2yi0p",
  // },
  // {
  //   src: "/school.jpg",
  //   title: "山大AI校园",
  //   sub: "山大AI校园小助手，为您的校园生活保驾护航。",
  //   navigate: "dJUIt21U3NQ2yi0p",
  // },
  // {
  //   src: "/school.jpg",
  //   title: "山大AI校园",
  //   sub: "山大AI校园小助手，为您的校园生活保驾护航。",
  //   navigate: "dJUIt21U3NQ2yi0p",
  // },
  // {
  //   src: "/school.jpg",
  //   title: "山大AI校园",
  //   sub: "山大AI校园小助手，为您的校园生活保驾护航。",
  //   navigate: "dJUIt21U3NQ2yi0p",
  // },
  // {
  //   src: "/school.jpg",
  //   title: "山大AI校园",
  //   sub: "山大AI校园小助手，为您的校园生活保驾护航。",
  //   navigate: "dJUIt21U3NQ2yi0p",
  // },
  // {
  //   src: "/school.jpg",
  //   title: "山大AI校园",
  //   sub: "山大AI校园小助手，为您的校园生活保驾护航。",
  //   navigate: "dJUIt21U3NQ2yi0p",
  // },
];
