export const AI_AGENTS_COMPONENTS = [
  {
    src: "/public/school.jpg",
    title: "山大AI校园",
    sub: "山大AI校园小助手，为您的校园生活保驾护航。",
    navigate: "dJUIt21U3NQ2yi0p",
  },
  {
    src: "/public/school.jpg",
    title: "山大AI校园",
    sub: "山大AI校园小助手，为您的校园生活保驾护航。",
    navigate: "dJUIt21U3NQ2yi0p",
  },
  {
    src: "/public/school.jpg",
    title: "山大AI校园",
    sub: "山大AI校园小助手，为您的校园生活保驾护航。",
    navigate: "dJUIt21U3NQ2yi0p",
  },
  {
    src: "/public/school.jpg",
    title: "山大AI校园",
    sub: "山大AI校园小助手，为您的校园生活保驾护航。",
    navigate: "dJUIt21U3NQ2yi0p",
  },
  {
    src: "/public/school.jpg",
    title: "山大AI校园",
    sub: "山大AI校园小助手，为您的校园生活保驾护航。",
    navigate: "dJUIt21U3NQ2yi0p",
  },
  {
    src: "/public/school.jpg",
    title: "山大AI校园",
    sub: "山大AI校园小助手，为您的校园生活保驾护航。",
    navigate: "dJUIt21U3NQ2yi0p",
  },
  {
    src: "/public/school.jpg",
    title: "山大AI校园",
    sub: "山大AI校园小助手，为您的校园生活保驾护航。",
    navigate: "dJUIt21U3NQ2yi0p",
  },
  {
    src: "/public/school.jpg",
    title: "山大AI校园",
    sub: "山大AI校园小助手，为您的校园生活保驾护航。",
    navigate: "dJUIt21U3NQ2yi0p",
  },
  {
    src: "/public/school.jpg",
    title: "山大AI校园",
    sub: "山大AI校园小助手，为您的校园生活保驾护航。",
    navigate: "dJUIt21U3NQ2yi0p",
  },
  {
    src: "/public/school.jpg",
    title: "山大AI校园",
    sub: "山大AI校园小助手，为您的校园生活保驾护航。",
    navigate: "dJUIt21U3NQ2yi0p",
  },
  {
    src: "/public/school.jpg",
    title: "山大AI校园",
    sub: "山大AI校园小助手，为您的校园生活保驾护航。",
    navigate: "dJUIt21U3NQ2yi0p",
  },
  {
    src: "/public/school.jpg",
    title: "山大AI校园",
    sub: "山大AI校园小助手，为您的校园生活保驾护航。",
    navigate: "dJUIt21U3NQ2yi0p",
  },
  {
    src: "/public/school.jpg",
    title: "山大AI校园",
    sub: "山大AI校园小助手，为您的校园生活保驾护航。",
    navigate: "dJUIt21U3NQ2yi0p",
  },
  {
    src: "/public/school.jpg",
    title: "山大AI校园",
    sub: "山大AI校园小助手，为您的校园生活保驾护航。",
    navigate: "dJUIt21U3NQ2yi0p",
  },
  {
    src: "/public/school.jpg",
    title: "山大AI校园",
    sub: "山大AI校园小助手，为您的校园生活保驾护航。",
    navigate: "dJUIt21U3NQ2yi0p",
  },
];
